# Production Multi-Site Configuration
# This example shows a production-ready configuration with security hardening

[server]
name = "BWS Production Server"

# Main website
[[sites]]
name = "main"
hostname = "example.com"
port = 443
static_dir = "examples/sites/static"
default = true

[sites.headers]
"X-Site-Name" = "Main Website"
"Strict-Transport-Security" = "max-age=31536000; includeSubDomains"
"X-Content-Type-Options" = "nosniff"
"X-Frame-Options" = "DENY"

[sites.ssl]
enabled = true
auto_cert = true

[sites.ssl.acme]
enabled = true
email = "admin@example.com"

# API subdomain
[[sites]]
name = "api"
hostname = "api.example.com"
port = 443
static_dir = "examples/sites/static-api"

[sites.headers]
"X-Site-Name" = "API Server"
"Access-Control-Allow-Origin" = "https://example.com"
"Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
"Access-Control-Allow-Headers" = "Content-Type, Authorization"

[sites.ssl]
enabled = true
auto_cert = true

[sites.ssl.acme]
enabled = true
email = "admin@example.com"

# Performance configuration
[performance]
worker_threads = 8
max_connections = 1000
keep_alive_timeout = 60
request_timeout = 30

# Security configuration
[security]
hide_server_header = true
max_request_size = "10MB"

[security.security_headers]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"X-XSS-Protection" = "1; mode=block"
"Strict-Transport-Security" = "max-age=31536000; includeSubDomains"

# Logging configuration
[logging]
level = "info"
format = "combined"
log_requests = true
