# BWS Production Configuration Example
# This configuration demonstrates production-ready setup with hot reload capabilities

[server]
name = "BWS Production Server"

# Performance settings
[performance]
worker_threads = 8
max_connections = 10000
keep_alive_timeout = 60
request_timeout = 120

# Security configuration
[security]
hide_server_header = true
max_request_size = "10MB"

# Main production site
[[sites]]
name = "main-site"
hostname = "example.com"
hostnames = ["www.example.com"]
port = 443
static_dir = "examples/sites/static"
default = true

[sites.ssl]
enabled = true
auto_cert = true

[sites.ssl.acme]
enabled = true
email = "admin@example.com"

[sites.headers]
"X-Environment" = "production"
"Cache-Control" = "public, max-age=3600"

# Proxy configuration
[sites.proxy]
enabled = true

[[sites.proxy.upstreams]]
name = "backend-api"
url = "http://127.0.0.1:3001"

[[sites.proxy.routes]]
path = "/api/"
upstream = "backend-api"

# API site
[[sites]]
name = "api-site"
hostname = "api.example.com"
port = 443
static_dir = "examples/sites/static-api"

[sites.ssl]
enabled = true
auto_cert = true

[sites.ssl.acme]
enabled = true
email = "admin@example.com"
