[book]
authors = ["Ben Liao"]
language = "en"
multilingual = false
src = "src"
title = "BWS Web Server Documentation"
description = "Complete documentation for BWS - A high-performance multi-site web server built with Pingora"

[build]
build-dir = "book"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/benliao/bws"
edit-url-template = "https://github.com/benliao/bws/edit/main/docs/{path}"
site-url = "https://benliao.github.io/bws/"

[output.html.search]
enable = true

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0
